# Copyright (C) 2020  Sutou Kouhei <kou@clear-code.com>
#
# This library is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library.  If not, see <http://www.gnu.org/licenses/>.

name: Test
on:
  - push
  - pull_request
jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "2.5"
          - "2.6"
          # - "2.7"
        runs-on:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    name: ${{ matrix.ruby-version}} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@master
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install Bundler
        run: |
          gem install bundler
      - name: Install dependencies
        run: |
          bundle install
      - name: Test
        run: |
          bundle exec rake
